name: deploy

on:
  workflow_run:
    workflows: ["check"]
    branches: [main]
    types:
      - completed
  # schedule:
    # - cron: "0 18 * * 4"

  workflow_dispatch:

jobs:
  heroku-build:
    runs-on: ubuntu-latest
    outputs:
      heroku-build_id: ${{ steps.build.outputs.heroku-build_id }}
    steps:
      - name: Wait for tests to succeed
        if: ${{ github.event.workflow_run.conclusion != 'success' }}
        run: exit 1
      - name: Go On
        if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
        run: |
          git config --global --add safe.directory $(pwd)
          git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} .
          ref=$(echo ${{ github.ref }} | sed -E -n -e 's/^refs\/[^/]*\/(.*)$/\1/p')
          git checkout $ref
        shell: bash
      - name: checkout
        uses: ./.github/checkout
      - name: build
        id: build
        #run: |
          #echo "::set-output name=heroku-build_id::$HEROKU-BUILD_ID"
      
      # - name: push
        # uses: ./.github/heroku-build
        # with:
          # app-name: "${{secrets.APP}}"
          # api-key: "${{secrets.KEY}}"
        run: |
          #echo "👊👊👊👊👊👊action begin👊👊👊👊👊👊"
          TZ='Asia/Shanghai'; export TZ
          echo "::set-output name=heroku-build_id::$HEROKU-BUILD_ID"
  
  heroku-deploy:
    needs: heroku-build 
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        run: |
            git config --global --add safe.directory $(pwd)
            git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} .
            ref=$(echo ${{ github.ref }} | sed -E -n -e 's/^refs\/[^/]*\/(.*)$/\1/p')
            git checkout $ref
            sleep 120
        shell: bash
      
      - name: checkout
        id: checkout
        uses: ./.github/checkout
      #- run: echo HEROKU BUILD SUCCESS ! ${{ needs.build.outputs.heroku-build_id }}
      - name: Generate 0 or 1
        id: generate_number
        run:  echo "::set-output name=random_number::$(($RANDOM % 2))"
      - name: Pass or fail
        if: ${{ steps.generate_number.outputs.random_number == 0 }}
        run: |
          sleep 10
          #echo "😊😊😊😊😊😊success excute shell😊😊😊😊😊😊"
          echo HEROKU BUILD SUCCESS ! ${{ needs.build.outputs.heroku-build_id }}
        #run: |
          #if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then exit 0; else exit 1; fi
      
      - name: heroku-deploy
        if:  ${{ success() }}
        # uses: ./.github/heroku-deploy
        # with:
          # heroku_api_key: ${{ secrets.KEY }}
          # heroku_app_name: ${{ secrets.APP }}
          # heroku_email: ${{ secrets.MAIL }}
        run: |
          DATE=`date +%Y%m%d%H%M%S`
          echo "current git push time: $DATE"
