name: myci-actions

on:
  schedule:
    - cron: "0 18 * * 4"

  workflow_dispatch:

jobs:
  myci-actions:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        run: |
            for f in $(ls -A); do
              rm -rf $f
            done

            git config --global --add safe.directory $(pwd
            git clone --quiet https://${{ github.token }}@github.com/${{ github.repository }} .
            
            ref_type=$(echo ${{ github.ref }} | sed -E -n -e 's/^refs\/([^/]*)\/.*$/\1/p')
            ref=$(echo ${{ github.ref }} | sed -E -n -e 's/^refs\/[^/]*\/(.*)$/\1/p')

            case $ref_type in
              pull)
                  git fetch origin +refs/pull/$ref:refs/remotes/origin/pull/$ref
                  ref="origin/pull/$ref"
                  ;;
              *)
                  ref=${{ github.sha }}
                  ;;
            esac

            git checkout $ref
        shell: bash
